import 'bloc/about_us_org_bloc.dart';import 'models/about_us_org_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/custom_icon_button.dart';class AboutUsOrgScreen extends StatelessWidget {const AboutUsOrgScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AboutUsOrgBloc>(create: (context) => AboutUsOrgBloc(AboutUsOrgState(aboutUsOrgModelObj: AboutUsOrgModel()))..add(AboutUsOrgInitialEvent()), child: AboutUsOrgScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<AboutUsOrgBloc, AboutUsOrgState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 20.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 49.v), SizedBox(height: 117.v, width: 331.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Text("lbl_about_us2".tr, style: theme.textTheme.displayLarge)), Align(alignment: Alignment.bottomCenter, child: Text("msg_need_help_feel".tr, style: CustomTextStyles.titleLargeInterBlack900_2))])), SizedBox(height: 37.v), SizedBox(height: 175.v, width: 307.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomCenter, child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_uni".tr, style: theme.textTheme.displayMedium), TextSpan(text: "lbl_ventures".tr, style: CustomTextStyles.displayMediumPrimary_1)]), textAlign: TextAlign.left)), CustomImageView(imagePath: ImageConstant.imgMaskGroup, height: 126.v, width: 144.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 71.h))])), SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLink, height: 38.adaptSize, width: 38.adaptSize, margin: EdgeInsets.only(top: 1.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 30.h, top: 1.v, bottom: 3.v), child: CustomIconButton(height: 38.adaptSize, width: 38.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgSkillIconsInstagram))), Padding(padding: EdgeInsets.only(left: 30.h, top: 1.v, bottom: 3.v), child: CustomIconButton(height: 38.adaptSize, width: 38.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgGroup352))), Padding(padding: EdgeInsets.only(left: 29.h), child: CustomIconButton(height: 42.v, width: 38.h, child: CustomImageView(imagePath: ImageConstant.imgFa6BrandsSquareXTwitter)))]), SizedBox(height: 36.v), Container(width: 316.h, margin: EdgeInsets.only(left: 48.h, right: 53.h), child: Text("msg_you_can_read_our".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallBlack900)), Text("lbl_here".tr, style: CustomTextStyles.headlineSmallBlueA400), SizedBox(height: 33.v), CustomImageView(imagePath: ImageConstant.img, height: 93.adaptSize, width: 93.adaptSize), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return SizedBox(height: 100.v, width: 416.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.fromLTRB(18.h, 15.v, 25.h, 15.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 11.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})]))), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v))])))])); } 
/// Navigates to the homeListOrgScreen when the action is triggered.
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListOrgScreen, ); } 
 }
