import 'bloc/event_categories_startups_bloc.dart';import 'models/event_categories_startups_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:kwstas_s_application2/widgets/app_bar/appbar_title.dart';import 'package:kwstas_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:kwstas_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:kwstas_s_application2/widgets/custom_outlined_button.dart';class EventCategoriesStartupsScreen extends StatelessWidget {const EventCategoriesStartupsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<EventCategoriesStartupsBloc>(create: (context) => EventCategoriesStartupsBloc(EventCategoriesStartupsState(eventCategoriesStartupsModelObj: EventCategoriesStartupsModel()))..add(EventCategoriesStartupsInitialEvent()), child: EventCategoriesStartupsScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<EventCategoriesStartupsBloc, EventCategoriesStartupsState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 7.v), child: Padding(padding: EdgeInsets.only(left: 37.h, right: 37.h, bottom: 5.v), child: Column(children: [Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 47.v), CustomOutlinedButton(text: "lbl_startups2".tr, margin: EdgeInsets.only(left: 11.h, right: 4.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL201, buttonTextStyle: CustomTextStyles.headlineSmallOnPrimarySemiBold), SizedBox(height: 23.v), Container(width: 313.h, margin: EdgeInsets.only(left: 25.h, right: 17.h), child: Text("msg_networking_events".tr, maxLines: 5, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.titleMedium)), SizedBox(height: 55.v), SizedBox(height: 275.v, width: 272.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgThinkbiz1, height: 275.v, width: 272.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPhHeartFill, height: 48.v, width: 46.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 1.h)), SizedBox(height: 179.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 89.h, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 1.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_15_may_2023".tr, style: theme.textTheme.bodySmall)), _buildPlanBizTelevision(context, bookNowText: "lbl_book_now".tr)])])))])), Container(margin: EdgeInsets.symmetric(horizontal: 42.h), padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineOnPrimary, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 2.h, right: 4.h), child: _buildPlanBiz(context, planBizText: "lbl_thinkbiz".tr, startUpsText: "lbl_startups".tr)), SizedBox(height: 13.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 19.v, width: 18.h), Padding(padding: EdgeInsets.only(left: 5.h, top: 3.v), child: Text("lbl_aegaleo_athens".tr, style: theme.textTheme.bodySmall))]), SizedBox(height: 4.v)])), SizedBox(height: 82.v), _buildThirtyOne(context)]))))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 69.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSettings, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_univentures".tr, margin: EdgeInsets.only(left: 18.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgOcticonThreeBars16, margin: EdgeInsets.fromLTRB(33.h, 33.v, 33.h, 32.v), onTap: () {onTapOcticonThreeBarsSixteen(context);})], styleType: Style.bgOutline); } 
/// Section Widget
Widget _buildThirtyOne(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 41.h), child: Column(children: [SizedBox(height: 275.v, width: 272.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPlanbiz1, height: 275.v, width: 272.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPhHeartBoldOnprimary, height: 44.v, width: 39.h, alignment: Alignment.centerRight), SizedBox(height: 184.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 23.v, width: 91.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgTelevisionOnprimary, height: 23.v, width: 91.h, radius: BorderRadius.circular(11.h), alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_25_may_2023".tr, style: theme.textTheme.bodySmall)))])), _buildPlanBizTelevision(context, bookNowText: "lbl_book_now".tr)])])))])), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 6.v), decoration: AppDecoration.outlineOnPrimary, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h, right: 4.h), child: _buildPlanBiz(context, planBizText: "lbl_planbiz".tr, startUpsText: "lbl_startups".tr)), SizedBox(height: 9.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 19.v, width: 18.h), Padding(padding: EdgeInsets.only(left: 6.h, top: 2.v), child: Text("lbl_marousi_athens".tr, style: theme.textTheme.bodySmall))]), SizedBox(height: 9.v)]))])); } 
/// Common widget
Widget _buildPlanBizTelevision(BuildContext context, {required String bookNowText, }) { return SizedBox(height: 21.v, width: 89.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgTelevisionPrimary, height: 21.v, width: 89.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Text(bookNowText, style: theme.textTheme.labelLarge!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1)))),GestureDetector(
                onTap: () {
                  Navigator.of(context).pushNamed(AppRoutes.thinkBizScreen);
                })])); } 
/// Common widget
Widget _buildPlanBiz(BuildContext context, {required String planBizText, required String startUpsText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text(planBizText, style: CustomTextStyles.titleMediumBlack900_1.copyWith(color: appTheme.black900))), Padding(padding: EdgeInsets.only(top: 2.v), child: Text(startUpsText, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.black900.withOpacity(0.5))))]); } 
/// Navigates to the homeListScreen when the action is triggered.
onTapOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 
 }
