name: kwstas_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  permission_handler: ^11.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.7

  # Add your other dependencies below
  sqflite: ^2.0.0+4
  path_provider: ^2.0.9
  
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  google_maps_flutter: ^2.1.7
  location: ^5.0.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  sqflite_common_ffi: ^2.3.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsThin.ttf
          weight: 300
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsItalic.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsBlack.ttf
          weight: 900
        - asset: assets/fonts/PoppinsBlackItalic.ttf
          weight: 900
        - asset: assets/fonts/PoppinsBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/PoppinsExtraBold.ttf
          weight: 800
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterExtraLight.ttf
          weight: 200
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
