import 'bloc/plan_biz_bloc.dart';import 'models/plan_biz_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';class PlanBizScreen extends StatelessWidget {const PlanBizScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PlanBizBloc>(create: (context) => PlanBizBloc(PlanBizState(PlanBizModelObj: PlanBizModel()))..add(PlanBizInitialEvent()), child: PlanBizScreen()); }
@override Widget build(BuildContext context) { return BlocBuilder<PlanBizBloc, PlanBizState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 7.h, right: 7.h, bottom: 19.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 62.v), _buildStartUpsRow(context), SizedBox(height: 43.v), CustomImageView(imagePath: ImageConstant.imgPlanbiz1308x320, height: 308.v, width: 320.h), SizedBox(height: 31.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 45.v, width: 43.h), Padding(padding: EdgeInsets.only(left: 7.h, top: 9.v), child: Text("lbl_marousi_athens".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMingcuteTimeLine, height: 42.v, width: 43.h), Padding(padding: EdgeInsets.only(left: 7.h, top: 6.v), child: Text("lbl_25_may_2023".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRiMoneyDollarCircleLine, height: 43.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 9.h, bottom: 5.v), child: Text("lbl_free".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 27.v), GestureDetector(onTap: () {onTapFourteen(context);}, child: SizedBox(height: 48.v, width: 255.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 46.v, width: 255.h, decoration: BoxDecoration(color: theme.colorScheme.primary.withOpacity(0.21), borderRadius: BorderRadius.circular(20.h), border: Border.all(color: theme.colorScheme.primary, width: 1.h)))), Align(alignment: Alignment.center, child: GestureDetector(
 onTap: () {NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, );context.read<PlanBizBloc>().add(BookEvent(eventId: "planbiz"));},
 child: state.isBooked ? Text("Booked") : Text("Book Now"),))]))), SizedBox(height: 28.v), Container(width: 390.h, margin: EdgeInsets.only(left: 19.h, right: 7.h), child: Text("msg_planbiz_is_an_immersive".tr, maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeBlack900Light))]))))]))));}); }
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v),onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Section Widget
Widget _buildStartUpsRow(BuildContext context) {return BlocBuilder<PlanBizBloc, PlanBizState>(builder: (context, state) {return Padding(padding: EdgeInsets.symmetric(horizontal: 33.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_startups".tr, style: CustomTextStyles.titleLargeBlack900), Text("lbl_planbiz".tr, style: CustomTextStyles.displayMediumSemiBold)]), Spacer(flex: 54), Container(width: 62.h, margin: EdgeInsets.only(top: 39.v, bottom: 7.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgIconamoonStarFill, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 4.v, bottom: 7.v)), Text("lbl_4_9".tr, style: CustomTextStyles.headlineSmallBlack900)])), Spacer(flex: 45), GestureDetector(
    onTap: () => context.read<PlanBizBloc>().add(FavoriteEvent(eventId: "planbiz")),
    child: Icon(state.isFavorited ? Icons.favorite : Icons.favorite_border),)])); });}
/// Navigates to the bookNowLinkScreen when the action is triggered.
onTapFourteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, ); } 
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 

 }
