import 'bloc/party_at_ntua_bloc.dart';import 'models/party_at_ntua_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';class PartyAtNtuaScreen extends StatelessWidget {const PartyAtNtuaScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PartyAtNtuaBloc>(create: (context) => PartyAtNtuaBloc(PartyAtNtuaState(PartyAtNtuaModelObj: PartyAtNtuaModel()))..add(PartyAtNtuaInitialEvent()), child: PartyAtNtuaScreen()); }
@override Widget build(BuildContext context) { return BlocBuilder<PartyAtNtuaBloc, PartyAtNtuaState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 7.h, right: 7.h, bottom: 11.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 61.v), _buildUniversityRow(context), SizedBox(height: 50.v), CustomImageView(imagePath: ImageConstant.imgNtuaParty2308x320, height: 308.v, width: 320.h), SizedBox(height: 31.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 45.v, width: 43.h, margin: EdgeInsets.only(bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 7.h, top: 11.v), child: Text("msg_zografou_athens".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMingcuteTimeLine, height: 42.v, width: 43.h), Padding(padding: EdgeInsets.only(left: 7.h, top: 6.v), child: Text("lbl_30_may_2023".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRiMoneyDollarCircleLine, height: 43.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 9.h, bottom: 5.v), child: Text("lbl_52".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 31.v), GestureDetector(onTap: () {onTapFourteen(context);}, child: SizedBox(height: 48.v, width: 255.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 46.v, width: 255.h, decoration: BoxDecoration(color: theme.colorScheme.primary.withOpacity(0.21), borderRadius: BorderRadius.circular(20.h), border: Border.all(color: theme.colorScheme.primary, width: 1.h)))), Align(alignment: Alignment.center, child: GestureDetector(
 onTap: () {NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, );context.read<PartyAtNtuaBloc>().add(BookEvent(eventId: "partyatntua"));},
 child: state.isBooked ? Text("Booked") : Text("Book Now"),))]))), SizedBox(height: 32.v), Container(width: 386.h, margin: EdgeInsets.only(left: 14.h, right: 15.h), child: Text("msg_party_at_ntua_is2".tr, maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeBlack900Light))]))))]))));}); }
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Section Widget
Widget _buildUniversityRow(BuildContext context) {return BlocBuilder<PartyAtNtuaBloc, PartyAtNtuaState>(builder: (context, state) { return Padding(padding: EdgeInsets.only(left: 34.h, right: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_university".tr, style: CustomTextStyles.titleLargeBlack900), Text("lbl_party_at_ntua".tr, style: CustomTextStyles.headlineLargeSemiBold)]), CustomImageView(imagePath: ImageConstant.imgIconamoonStarFill, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 17.h, top: 36.v, bottom: 17.v)), Padding(padding: EdgeInsets.only(left: 5.h, top: 31.v, bottom: 9.v), child: Text("lbl_5_0".tr, style: CustomTextStyles.headlineSmallBlack900)), GestureDetector(
 onTap: () => context.read<PartyAtNtuaBloc>().add(FavoriteEvent(eventId: "partyatntua")),
 child: Icon(state.isFavorited ? Icons.favorite : Icons.favorite_border),)])); });}
/// Navigates to the bookNowLinkScreen when the action is triggered.
onTapFourteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, ); } 
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 
 }
