import 'bloc/tedxaueb_pangea_main_event_bloc.dart';import 'models/tedxaueb_pangea_main_event_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';class TedxauebPangeaMainEventScreen extends StatelessWidget {const TedxauebPangeaMainEventScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<TedxauebPangeaMainBloc>(create: (context) => TedxauebPangeaMainBloc(TedxauebPangeaMainState(TedxauebPangeaMainEventModelObj: TedxauebPangeaMainEventModel()))..add(TedxauebPangeaMainInitialEvent()), child: TedxauebPangeaMainEventScreen()); }
@override Widget build(BuildContext context) { return BlocBuilder<TedxauebPangeaMainBloc, TedxauebPangeaMainState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 7.h, right: 7.h, bottom: 11.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 59.v), _buildTedxEventsRow(context), SizedBox(height: 23.v), SizedBox(height: 308.v, width: 320.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(height: 296.v, width: 320.h, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.25), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))]))), CustomImageView(imagePath: ImageConstant.imgPangea1, height: 296.v, width: 320.h, alignment: Alignment.topCenter)])), SizedBox(height: 35.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 45.v, width: 43.h), Padding(padding: EdgeInsets.only(left: 7.h, top: 9.v), child: Text("msg_viktoria_athens".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMingcuteTimeLine, height: 42.v, width: 43.h), Padding(padding: EdgeInsets.only(left: 7.h, top: 6.v), child: Text("lbl_25_may_2023".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRiMoneyDollarCircleLine, height: 43.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 9.h, bottom: 5.v), child: Text("lbl_free".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 31.v), GestureDetector(onTap: () {onTapFourteen(context);}, child: SizedBox(height: 48.v, width: 255.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 46.v, width: 255.h, decoration: BoxDecoration(color: theme.colorScheme.primary.withOpacity(0.21), borderRadius: BorderRadius.circular(20.h), border: Border.all(color: theme.colorScheme.primary, width: 1.h)))), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, );context.read<TedxauebPangeaMainBloc>().add(BookEvent(eventId: "pangea"));},
 child: state.isBooked ? Text("Booked") : Text("Book Now"),))]))), SizedBox(height: 32.v), Container(width: 376.h, margin: EdgeInsets.only(left: 18.h, right: 21.h), child: Text("msg_tedxaueb_pangea4".tr, maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeBlack900Light))]))))]))));}); }
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v),onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Section Widget
Widget _buildTedxEventsRow(BuildContext context) {return BlocBuilder<TedxauebPangeaMainBloc, TedxauebPangeaMainState>(builder: (context, state) { return Padding(padding: EdgeInsets.only(left: 32.h, right: 26.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_tedxevents".tr, style: CustomTextStyles.titleLargeBlack900)), SizedBox(width: 219.h, child: Text("msg_tedxaueb_pangea3".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallBlack900SemiBold))]), CustomImageView(imagePath: ImageConstant.imgIconamoonStarFill, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 15.h, top: 64.v, bottom: 12.v)), Padding(padding: EdgeInsets.only(left: 5.h, top: 61.v, bottom: 3.v), child: Text("lbl_4_9".tr, style: CustomTextStyles.headlineSmallBlack900)), GestureDetector(onTap: () => context.read<TedxauebPangeaMainBloc>().add(FavoriteEvent(eventId: "pangea")),
 child: Icon(state.isFavorited ? Icons.favorite : Icons.favorite_border),)])); });}
/// Navigates to the bookNowLinkScreen when the action is triggered.
onTapFourteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, ); } 
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 

 }
