import 'bloc/think_biz_bloc.dart';import 'models/think_biz_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';class ThinkBizScreen extends StatelessWidget {const ThinkBizScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ThinkBizBloc>(create: (context) => ThinkBizBloc(ThinkBizState(thinkBizModelObj: ThinkBizModel()))..add(ThinkBizInitialEvent()), child: ThinkBizScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ThinkBizBloc, ThinkBizState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 7.h, right: 7.h, bottom: 19.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 62.v), _buildStartUpsRow(context), SizedBox(height: 34.v), CustomImageView(imagePath: ImageConstant.imgThinkbiz2, height: 308.v, width: 320.h), SizedBox(height: 40.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 45.v, width: 43.h, margin: EdgeInsets.only(bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 7.h, top: 11.v), child: Text("lbl_aegaleo_athens".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMingcuteTimeLine, height: 42.v, width: 43.h), Padding(padding: EdgeInsets.only(left: 7.h, top: 6.v), child: Text("lbl_13_may_2023".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 62.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRiMoneyDollarCircleLine, height: 43.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 9.h, bottom: 5.v), child: Text("lbl_free".tr, style: CustomTextStyles.headlineSmallBlack900))]))), SizedBox(height: 27.v), GestureDetector(onTap: () {onTapFourteen(context);}, child: SizedBox(height: 48.v, width: 255.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 46.v, width: 255.h, decoration: BoxDecoration(color: theme.colorScheme.primary.withOpacity(0.21), borderRadius: BorderRadius.circular(20.h), border: Border.all(color: theme.colorScheme.primary, width: 1.h)))), Align(alignment: Alignment.center, child: GestureDetector(
 onTap: () {NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, );context.read<ThinkBizBloc>().add(BookEvent(eventId: "thinkbiz"));},
 child: state.isBooked ? Text("Booked") : Text("Book Now"),
))]))), SizedBox(height: 28.v), Container(width: 371.h, margin: EdgeInsets.symmetric(horizontal: 22.h), child: Text("msg_thinkbiz_is_an_inspiring".tr, maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeBlack900Light))]))))]))));}); }
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Section Widget
Widget _buildStartUpsRow(BuildContext context) { return BlocBuilder<ThinkBizBloc, ThinkBizState>(builder: (context, state){return Padding(padding: EdgeInsets.only(left: 34.h, right: 17.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_startups".tr, style: CustomTextStyles.titleLargeBlack900), Text("lbl_thinkbiz".tr, style: CustomTextStyles.displayMediumSemiBold)]), Spacer(flex: 37), CustomImageView(imagePath: ImageConstant.imgIconamoonStarFill, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 44.v, bottom: 14.v)), Padding(padding: EdgeInsets.only(left: 4.h, top: 39.v, bottom: 7.v), child: Text("lbl_4_9".tr, style: CustomTextStyles.headlineSmallBlack900)), Spacer(flex: 62), GestureDetector(
 onTap: () => context.read<ThinkBizBloc>().add(FavoriteEvent(eventId: "thinkbiz")),
 child: Icon(state.isFavorited ? Icons.favorite : Icons.favorite_border),
 )])); });}
/// Navigates to the bookNowLinkScreen when the action is triggered.
onTapFourteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.bookNowLinkScreen, ); } 
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 
 }
