import 'bloc/setup_your_account_student_no_bloc.dart';import 'models/setup_your_account_student_no_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/custom_outlined_button.dart';import 'package:kwstas_s_application2/widgets/custom_text_form_field.dart';class SetupYourAccountStudentNoScreen extends StatelessWidget {const SetupYourAccountStudentNoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SetupYourAccountStudentNoBloc>(create: (context) => SetupYourAccountStudentNoBloc(SetupYourAccountStudentNoState(setupYourAccountStudentNoModelObj: SetupYourAccountStudentNoModel()))..add(SetupYourAccountStudentNoInitialEvent()), child: SetupYourAccountStudentNoScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 44.h, vertical: 26.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), SizedBox(height: 33.v), Container(width: 329.h, margin: EdgeInsets.symmetric(horizontal: 6.h), child: Text("msg_some_more_steps".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.displayMedium)), SizedBox(height: 47.v), SizedBox(height: 63.v, width: 341.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLetsIconsArro, height: 43.v, width: 46.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 14.h)), BlocSelector<SetupYourAccountStudentNoBloc, SetupYourAccountStudentNoState, TextEditingController?>(selector: (state) => state.questionOneController, builder: (context, questionOneController) {return CustomTextFormField(width: 341.h, controller: questionOneController, hintText: "msg_no_i_am_not_a_student".tr, hintStyle: theme.textTheme.titleLarge!, alignment: Alignment.center, contentPadding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v));})])), SizedBox(height: 9.v), SizedBox(height: 63.v, width: 341.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLetsIconsArro, height: 43.v, width: 46.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 14.h)), BlocSelector<SetupYourAccountStudentNoBloc, SetupYourAccountStudentNoState, TextEditingController?>(selector: (state) => state.questionTwoController, builder: (context, questionTwoController) {return CustomTextFormField(width: 341.h, controller: questionTwoController, hintText: "msg_yes_i_am_an_organization".tr, hintStyle: theme.textTheme.titleLarge!, textInputAction: TextInputAction.done, alignment: Alignment.center, contentPadding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v));})])), SizedBox(height: 9.v), Container(width: 341.h, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 13.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder31), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), TextField(decoration: InputDecoration(
                      labelText: "What do you like?",
                      border: OutlineInputBorder(),))])), SizedBox(height: 29.v), CustomOutlinedButton(text: "lbl_finish".tr, buttonStyle: CustomButtonStyles.outlinePrimaryTL313, onPressed: () {onTapFinish(context);}), SizedBox(height: 5.v)])))); } 
/// Navigates to the successfullySignedUpOrgScreen when the action is triggered.
onTapFinish(BuildContext context) { NavigatorService.pushNamed(AppRoutes.successfullySignedUpScreen, ); } 
 }
