import 'bloc/gmail_email_login_bloc.dart';import 'models/gmail_email_login_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/core/utils/validation_functions.dart';import 'package:kwstas_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:kwstas_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:kwstas_s_application2/widgets/custom_elevated_button.dart';import 'package:kwstas_s_application2/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class GmailEmailLoginScreen extends StatelessWidget {GmailEmailLoginScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<GmailEmailLoginBloc>(create: (context) => GmailEmailLoginBloc(GmailEmailLoginState(gmailEmailLoginModelObj: GmailEmailLoginModel()))..add(GmailEmailLoginInitialEvent()), child: GmailEmailLoginScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 48.h, vertical: 23.v), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgClock, height: 37.v, width: 40.h, margin: EdgeInsets.only(bottom: 11.v)), CustomImageView(imagePath: ImageConstant.imgContrast, height: 24.v, width: 28.h, margin: EdgeInsets.only(left: 2.h, top: 13.v, bottom: 11.v)), CustomImageView(imagePath: ImageConstant.imgContrastOrange300, height: 23.v, width: 27.h, margin: EdgeInsets.only(left: 2.h, top: 13.v, bottom: 11.v)), CustomImageView(imagePath: ImageConstant.imgContrastBlueA200, height: 35.v, width: 27.h, margin: EdgeInsets.only(left: 1.h, top: 13.v)), Padding(padding: EdgeInsets.only(left: 3.h), child: SizedBox(height: 46.v, child: VerticalDivider(width: 5.h, thickness: 5.v, color: appTheme.greenA700, endIndent: 11.h))), CustomImageView(imagePath: ImageConstant.imgContrastRed500, height: 23.v, width: 24.h, margin: EdgeInsets.only(left: 4.h, top: 13.v, bottom: 11.v))]), SizedBox(height: 30.v), Container(width: 245.h, margin: EdgeInsets.only(left: 45.h, right: 44.h), child: Text("msg_sign_in_with_your".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeInterBlack900_1)), SizedBox(height: 55.v), BlocSelector<GmailEmailLoginBloc, GmailEmailLoginState, TextEditingController?>(selector: (state) => state.phoneController, builder: (context, phoneController) {return CustomTextFormField(controller: phoneController, hintText: "lbl_email_or_phone".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 22.v), borderDecoration: TextFormFieldStyleHelper.outlineBlack, fillColor: theme.colorScheme.onPrimary.withOpacity(1));}), SizedBox(height: 53.v), CustomElevatedButton(width: 100.h, text: "lbl_next".tr, margin: EdgeInsets.only(right: 8.h), buttonStyle: CustomButtonStyles.fillBlueA, buttonTextStyle: CustomTextStyles.titleLargeInterOnPrimaryBold, onPressed: () {onTapNext(context);}, alignment: Alignment.centerRight), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 66.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVectorBlack90022x24, margin: EdgeInsets.fromLTRB(15.h, 16.v, 391.h, 17.v))); } 
/// Navigates to the gmailPasswordLoginScreen when the action is triggered.
onTapNext(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gmailPasswordLoginScreen, ); } 
 }
