import 'bloc/think_biz_profile_org_bloc.dart';import 'models/think_biz_profile_org_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/core/utils/validation_functions.dart';import 'package:kwstas_s_application2/widgets/custom_text_form_field.dart';import 'package:kwstas_s_application2/presentation/profile_photo_org_dialog/profile_photo_org_dialog.dart';
// ignore_for_file: must_be_immutable
class ThinkBizProfileOrgScreen extends StatelessWidget {ThinkBizProfileOrgScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<ThinkBizProfileOrgBloc>(create: (context) => ThinkBizProfileOrgBloc(ThinkBizProfileOrgState(thinkBizProfileOrgModelObj: ThinkBizProfileOrgModel()))..add(ThinkBizProfileOrgInitialEvent()), child: ThinkBizProfileOrgScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 7.h, right: 7.h, bottom: 174.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 49.v), Text("lbl_my_profile2".tr, style: theme.textTheme.displayLarge), SizedBox(height: 26.v), _buildThinkbizThreeColumn(context), SizedBox(height: 83.v), Padding(padding: EdgeInsets.only(left: 35.h, right: 29.h), child: BlocBuilder<ThinkBizProfileOrgBloc, ThinkBizProfileOrgState>(builder: (context, state) {return CustomTextFormField(controller: state.appTitleController, hintText: "lbl_thinkbiz".tr, hintStyle: CustomTextStyles.headlineSmallBlack900_1, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {context.read<ThinkBizProfileOrgBloc>().add(ChangePasswordVisibilityEvent(value: !state.isShowPassword));}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 5.v, 4.h, 11.v), child: CustomImageView(imagePath: ImageConstant.imgCloseGray70001, height: 21.v, width: 20.h))), suffixConstraints: BoxConstraints(maxHeight: 37.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword, contentPadding: EdgeInsets.only(left: 5.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);})), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 35.h, right: 28.h), child: BlocBuilder<ThinkBizProfileOrgBloc, ThinkBizProfileOrgState>(builder: (context, state) {return CustomTextFormField(controller: state.passwordController, hintText: "lbl_reset_password".tr, hintStyle: CustomTextStyles.headlineSmallBlack900_1, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {context.read<ThinkBizProfileOrgBloc>().add(ChangePasswordVisibilityEvent1(value: !state.isShowPassword1));}, child: Container(margin: EdgeInsets.only(left: 30.h, top: 6.v, bottom: 5.v), child: CustomImageView(imagePath: ImageConstant.imgArrowleftIndigoA400, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 36.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword1, contentPadding: EdgeInsets.only(left: 5.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);})), SizedBox(height: 17.v), _buildMdiTickStack(context)]))))]))))); } 
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Section Widget
Widget _buildThinkbizThreeColumn(BuildContext context) { return Column(children: [SizedBox(height: 145.adaptSize, width: 145.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgThinkbiz1, height: 145.adaptSize, width: 145.adaptSize, alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: 139.adaptSize, width: 139.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(69.h), border: Border.all(color: appTheme.black900, width: 1.h))))])), SizedBox(height: 5.v), GestureDetector(onTap: () {onTapTxtChangeprofilepicture(context);}, child: Text("msg_change_profile_picture".tr, style: theme.textTheme.bodyMedium))]); } 
/// Section Widget
Widget _buildMdiTickStack(BuildContext context) { return SizedBox(height: 36.v, width: 352.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMditick, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 2.v)), Align(alignment: Alignment.center, child: SizedBox(height: 36.v, width: 352.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 4.v), child: SizedBox(width: 352.h, child: Divider(color: appTheme.gray600)))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 5.h), child: Text("msg_email_thinkbiz_gmail_com".tr, style: CustomTextStyles.headlineSmallBlack900_1)))])))])); } 
/// Navigates to the homeListOrgScreen when the action is triggered.
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListOrgScreen, ); } 

/// Displays a dialog with the [ProfilePhotoOrgDialog] content.
onTapTxtChangeprofilepicture(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: ProfilePhotoOrgDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
