import 'bloc/home_bloc.dart';import 'models/home_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/custom_outlined_button.dart';class HomeScreen extends StatelessWidget {const HomeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<HomeBloc>(create: (context) => HomeBloc(HomeState(homeModelObj: HomeModel()))..add(HomeInitialEvent()), child: HomeScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<HomeBloc, HomeState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 20.v), child : SingleChildScrollView( child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 80.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_univentures2".tr, style: CustomTextStyles.displaySmallBlack900), TextSpan(text: "lbl_for_you".tr, style: theme.textTheme.displaySmall)]), textAlign: TextAlign.left), SizedBox(height: 6.v), Container(width: 380.h, margin: EdgeInsets.only(left: 20.h, right: 16.h), child: Text("msg_learn_everything".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeBlack900_1)), SizedBox(height: 79.v), CustomOutlinedButton(text: "lbl_search_an_event".tr, buttonStyle: ElevatedButton.styleFrom(
    backgroundColor: CustomTextStyles.displayMediumPrimary_1.color), margin: EdgeInsets.only(left: 41.h, right: 36.h), onPressed: () {onTapSearchAnEvent(context);}), SizedBox(height: 71.v), CustomImageView(imagePath: ImageConstant.imgTeamIllustration, height: 304.v, width: 358.h)])))));}); } 
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(margin: EdgeInsets.only(right: 2.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Navigates to the homeListScreen when the action is triggered.
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 
/// Navigates to the searchAnEventScreen when the action is triggered.
onTapSearchAnEvent(BuildContext context) { NavigatorService.pushNamed(AppRoutes.searchAnEventScreen, ); } 
 }
