import 'bloc/home_org_bloc.dart';import 'models/home_org_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/custom_outlined_button.dart';class HomeOrgScreen extends StatelessWidget {const HomeOrgScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<HomeOrgBloc>(create: (context) => HomeOrgBloc(HomeOrgState(homeOrgModelObj: HomeOrgModel()))..add(HomeOrgInitialEvent()), child: HomeOrgScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<HomeOrgBloc, HomeOrgState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 20.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 38.v), Container(width: 343.h, margin: EdgeInsets.only(left: 44.h, right: 30.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_univentures2".tr, style: CustomTextStyles.displaySmallBlack900), TextSpan(text: "msg_for_your_organization".tr, style: theme.textTheme.displaySmall)]), textAlign: TextAlign.center)), SizedBox(height: 6.v), Container(width: 358.h, margin: EdgeInsets.only(left: 33.h, right: 25.h), child: Text("msg_promote_your_university".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargeBlack900_1)), SizedBox(height: 55.v), CustomOutlinedButton(text: "lbl_upload_an_event".tr, margin: EdgeInsets.only(left: 41.h, right: 36.h), onPressed: () {onTapUploadAnEvent(context);}), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(margin: EdgeInsets.only(right: 2.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Navigates to the homeListOrgScreen when the action is triggered.
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListOrgScreen, ); } 
/// Navigates to the thinkBizUploadAnEventOrgScreen when the action is triggered.
onTapUploadAnEvent(BuildContext context) { NavigatorService.pushNamed(AppRoutes.thinkBizUploadAnEventOrgScreen, ); } 
 }
