import 'bloc/setup_your_account_student_four_bloc.dart';import 'models/setup_your_account_student_four_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/custom_outlined_button.dart';class SetupYourAccountStudentFourScreen extends StatelessWidget {const SetupYourAccountStudentFourScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SetupYourAccountStudentFourBloc>(create: (context) => SetupYourAccountStudentFourBloc(SetupYourAccountStudentFourState(setupYourAccountStudentFourModelObj: SetupYourAccountStudentFourModel()))..add(SetupYourAccountStudentFourInitialEvent()), child: SetupYourAccountStudentFourScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<SetupYourAccountStudentFourBloc, SetupYourAccountStudentFourState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 44.h, vertical: 26.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), SizedBox(height: 33.v), Container(width: 329.h, margin: EdgeInsets.symmetric(horizontal: 6.h), child: Text("msg_some_more_steps".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.displayMedium)), SizedBox(height: 62.v), SizedBox(height: 63.v, width: 341.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLetsIconsArro, height: 43.v, width: 46.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 14.h, bottom: 8.v)), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder31), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 5.v), Text("msg_are_you_a_student".tr, style: theme.textTheme.titleLarge)])))])), Container(margin: EdgeInsets.symmetric(horizontal: 14.h), padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 4.v), decoration: AppDecoration.outlinePrimary2.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), GestureDetector(onTap: () {onTapTxtYesIAmAStudent(context);}, child: Text("msg_yes_i_am_a_student".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 7.v), Divider(color: theme.colorScheme.primary, indent: 22.h, endIndent: 22.h), SizedBox(height: 6.v), GestureDetector(onTap: () {onTapTxtNoIAmNotAStudent(context);}, child: Text("msg_no_i_am_not_a_student".tr, style: theme.textTheme.headlineSmall))])), SizedBox(height: 55.v), CustomOutlinedButton(text: "lbl_finish".tr, buttonStyle: CustomButtonStyles.outlinePrimaryTL312), SizedBox(height: 5.v)]))));}); } 
/// Navigates to the setupYourAccountStudentYesScreen when the action is triggered.
onTapTxtYesIAmAStudent(BuildContext context) { NavigatorService.pushNamed(AppRoutes.setupYourAccountStudentYesScreen, ); } 
/// Navigates to the setupYourAccountStudentNoTwoScreen when the action is triggered.
onTapTxtNoIAmNotAStudent(BuildContext context) { NavigatorService.pushNamed(AppRoutes.setupYourAccountStudentNoTwoScreen, ); } 
 }
