import 'bloc/my_events_org_bloc.dart';import 'models/my_events_org_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/custom_elevated_button.dart';class MyEventsOrgScreen extends StatelessWidget {const MyEventsOrgScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MyEventsOrgBloc>(create: (context) => MyEventsOrgBloc(MyEventsOrgState(myEventsOrgModelObj: MyEventsOrgModel()))..add(MyEventsOrgInitialEvent()), child: MyEventsOrgScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<MyEventsOrgBloc, MyEventsOrgState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 7.h, right: 7.h, bottom: 203.v), child: Column(children: [_buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 35.v), Text("lbl_my_events".tr, style: theme.textTheme.displayLarge), SizedBox(height: 52.v), SizedBox(height: 303.v, width: 333.h, child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgThinkbiz2, height: 303.v, width: 333.h, alignment: Alignment.center), Align(alignment: Alignment.bottomLeft, child: Container(width: 84.h, margin: EdgeInsets.only(left: 15.h, bottom: 15.v), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 1.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_15_may_2023".tr, style: theme.textTheme.bodySmall)))])), Container(margin: EdgeInsets.only(left: 38.h, right: 45.h), padding: EdgeInsets.fromLTRB(13.h, 10.v, 13.h, 8.v), decoration: AppDecoration.outlineBlack9003, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(left: 4.h, bottom: 1.v), child: Text("lbl_thinkbiz".tr, style: CustomTextStyles.titleLargeBlack900SemiBold)), CustomElevatedButton(height: 32.v, width: 128.h, text: "lbl_view_modify".tr, buttonTextStyle: theme.textTheme.labelLarge!, onPressed: () {onTapVIEWMODIFY(context);})]))]))))]))));}); } 
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Navigates to the homeListOrgScreen when the action is triggered.
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListOrgScreen, ); } 
/// Navigates to the thinkBizOrgScreen when the action is triggered.
onTapVIEWMODIFY(BuildContext context) { NavigatorService.pushNamed(AppRoutes.thinkBizOrgScreen, ); } 
 }
