import 'bloc/search_an_event_gps_map_one_bloc.dart';import 'dart:async';import 'models/search_an_event_gps_map_one_model.dart';import 'package:flutter/material.dart';import 'package:google_maps_flutter/google_maps_flutter.dart';import 'package:kwstas_s_application2/core/app_export.dart';
// ignore_for_file: must_be_immutable
class SearchAnEventGpsMapOneScreen extends StatelessWidget {SearchAnEventGpsMapOneScreen({Key? key}) : super(key: key);

Completer<GoogleMapController> googleMapController = Completer();

static Widget builder(BuildContext context) { return BlocProvider<SearchAnEventGpsMapOneBloc>(create: (context) => SearchAnEventGpsMapOneBloc(SearchAnEventGpsMapOneState(searchAnEventGpsMapOneModelObj: SearchAnEventGpsMapOneModel()))..add(SearchAnEventGpsMapOneInitialEvent()), child: SearchAnEventGpsMapOneScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<SearchAnEventGpsMapOneBloc, SearchAnEventGpsMapOneState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 20.v), _buildSettingsRow(context), SizedBox(height: 7.v), Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 21.v), SizedBox(height: 711.v, width: 429.h, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgMapOfBirmingham699x429, height: 699.v, width: 429.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 48.v, width: 30.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 126.h, bottom: 256.v), onTap: () {onTapImgLinkedin(context);}), Align(alignment: Alignment.bottomRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 15.v, width: 121.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(height: 15.v, width: 121.h, decoration: BoxDecoration(color: appTheme.gray100Cc))), Align(alignment: Alignment.bottomCenter, child: Text("msg_map_data_2019_google".tr, style: CustomTextStyles.bodySmallRobotoBlack900))])), Container(width: 70.h, margin: EdgeInsets.only(left: 1.h), padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 1.v), decoration: AppDecoration.fillGrayCc, child: Text("lbl_terms_of_use".tr, style: CustomTextStyles.bodySmallRobotoBlack900)), Container(height: 15.v, width: 93.h, margin: EdgeInsets.only(left: 1.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgRectangle32, height: 15.v, width: 93.h, alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Text("msg_report_a_map_error".tr, style: CustomTextStyles.bodySmallRobotoBlack900))]))])), CustomImageView(imagePath: ImageConstant.imgSettingsBlueA20002, height: 19.v, width: 61.h, alignment: Alignment.bottomLeft, margin: EdgeInsets.only(left: 7.h, bottom: 3.v)), _buildMapStack(context)]))]))));}); } 
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 7.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v), onTap: () {onTapImgOcticonThreeBarsSixteen(context);})])); } 
/// Section Widget
Widget _buildMapStack(BuildContext context) { return SizedBox(height: 402.v, width: 417.h, child: GoogleMap(mapType: MapType.normal, initialCameraPosition: CameraPosition(target: LatLng(37.43296265331129, -122.08832357078792), zoom: 14.4746), onMapCreated: (GoogleMapController controller) {googleMapController.complete(controller);}, zoomControlsEnabled: false, zoomGesturesEnabled: false, myLocationButtonEnabled: false, myLocationEnabled: false)); } 
/// Navigates to the homeListScreen when the action is triggered.
onTapImgOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 
/// Navigates to the searchAnEventGpsMapScreen when the action is triggered.
onTapImgLinkedin(BuildContext context) { NavigatorService.pushNamed(AppRoutes.searchAnEventGpsMapScreen, ); } 
 }
