import 'bloc/home_list_bloc.dart';import 'models/home_list_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';class HomeListScreen extends StatelessWidget {const HomeListScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<HomeListBloc>(create: (context) => HomeListBloc(HomeListState(homeListModelObj: HomeListModel()))..add(HomeListInitialEvent()), child: HomeListScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<HomeListBloc, HomeListState>(builder: (context, state) => GestureDetector(
          behavior: HitTestBehavior.translucent,
          onTap: () {
            // This will pop the current route off the navigation stack
            Navigator.pop(context);
          },child: Scaffold(body: SafeArea(child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 20.v), child: SingleChildScrollView( child: Column(children: [_buildSettingsRow(context), SizedBox(height: 5.v), Container(margin: EdgeInsets.only(left: 32.h, right: 29.h), padding: EdgeInsets.symmetric(horizontal: 63.h, vertical: 13.v), decoration: AppDecoration.outlinePrimary2.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [GestureDetector(onTap: () {onTapTxtHome(context);}, child: Text("lbl_home".tr, style: CustomTextStyles.headlineLargePrimary)), SizedBox(height: 8.v), Divider(color: theme.colorScheme.primary, indent: 2.h, endIndent: 4.h), SizedBox(height: 8.v), GestureDetector(onTap: () {onTapTxtEvents(context);}, child: Text("lbl_events".tr, style: CustomTextStyles.headlineLargePrimary)), SizedBox(height: 8.v), Divider(color: theme.colorScheme.primary, indent: 2.h, endIndent: 4.h), SizedBox(height: 7.v), GestureDetector(onTap: () {onTapTxtVolunteer(context);}, child: Text("lbl_volunteer".tr, style: CustomTextStyles.headlineLargePrimary)), SizedBox(height: 9.v), Divider(color: theme.colorScheme.primary, indent: 3.h, endIndent: 6.h), SizedBox(height: 11.v), SizedBox(height: 5.v), GestureDetector(onTap: () {onTapTxtMyProfile(context);}, child: Text("lbl_my_profile".tr, style: CustomTextStyles.headlineLargePrimary)), SizedBox(height: 5.v), Divider(color: theme.colorScheme.primary,indent: 2.h, endIndent: 3.h), SizedBox(height: 11.v), GestureDetector(onTap: () {onTapTxtMyFavorites(context);}, child: Text("lbl_my_favorites".tr, style: CustomTextStyles.headlineLargePrimary)), SizedBox(height: 5.v), Divider(color: theme.colorScheme.primary, indent: 2.h, endIndent: 3.h), SizedBox(height: 11.v), GestureDetector(onTap: () {onTapTxtMyBookings(context);}, child: Text("lbl_my_bookings".tr, style: CustomTextStyles.headlineLargePrimary)), SizedBox(height: 5.v), Divider(color: theme.colorScheme.primary, indent: 6.h), SizedBox(height: 12.v), GestureDetector(onTap: () {onTapTxtAboutUs(context);}, child: Text("lbl_about_us".tr, style: CustomTextStyles.headlineLargePrimary)), SizedBox(height: 4.v)]))]))))))); }
/// Section Widget
Widget _buildSettingsRow(BuildContext context) { return Container(margin: EdgeInsets.only(right: 2.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), Padding(padding: EdgeInsets.only(left: 18.h, top: 8.v, bottom: 12.v), child: Text("lbl_univentures".tr, style: theme.textTheme.headlineLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgOcticonThreeBars16, height: 35.v, width: 30.h, margin: EdgeInsets.only(top: 17.v, right: 6.h, bottom: 16.v))])); } 
/// Navigates to the homeScreen when the action is triggered.
onTapTxtHome(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
/// Navigates to the eventsScreen when the action is triggered.
onTapTxtEvents(BuildContext context) { NavigatorService.pushNamed(AppRoutes.eventsScreen, ); } 
onTapTxtAboutUs(BuildContext context) { NavigatorService.pushNamed(AppRoutes.aboutUsScreen, ); }
onTapTxtVolunteer(BuildContext context) { NavigatorService.pushNamed(AppRoutes.volunteerScreen, ); }
onTapTxtMyProfile(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); }
onTapTxtMyFavorites(BuildContext context) { NavigatorService.pushNamed(AppRoutes.favoritesScreen, ); }
onTapTxtMyBookings(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myBookingsScreen, ); }
onTapTxtMyProgress(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myProgressScreen, ); }
 }
