import 'bloc/event_categories_technology_bloc.dart';import 'models/event_categories_technology_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/app_bar/appbar_leading_image.dart';import 'package:kwstas_s_application2/widgets/app_bar/appbar_title.dart';import 'package:kwstas_s_application2/widgets/app_bar/appbar_trailing_image.dart';import 'package:kwstas_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:kwstas_s_application2/widgets/custom_outlined_button.dart';class EventCategoriesTechnologyScreen extends StatelessWidget {const EventCategoriesTechnologyScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<EventCategoriesTechnologyBloc>(create: (context) => EventCategoriesTechnologyBloc(EventCategoriesTechnologyState(eventCategoriesTechnologyModelObj: EventCategoriesTechnologyModel()))..add(EventCategoriesTechnologyInitialEvent()), child: EventCategoriesTechnologyScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<EventCategoriesTechnologyBloc, EventCategoriesTechnologyState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 7.v), child: Padding(padding: EdgeInsets.only(left: 37.h, right: 37.h, bottom: 5.v), child: Column(children: [Text("msg_unleash_your_academic".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 47.v), CustomOutlinedButton(text: "lbl_technology2".tr, margin: EdgeInsets.only(left: 11.h, right: 4.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL201, buttonTextStyle: CustomTextStyles.headlineSmallOnPrimarySemiBold), SizedBox(height: 23.v), Container(width: 310.h, margin: EdgeInsets.only(left: 26.h, right: 19.h), child: Text("msg_conferences_and".tr, maxLines: 5, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.titleMedium)), SizedBox(height: 56.v), SizedBox(height: 356.v, width: 272.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgTechconnect1, height: 275.v, width: 272.h, alignment: Alignment.topCenter), CustomImageView(imagePath: ImageConstant.imgPhHeartFillOnprimary, height: 48.v, width: 46.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 13.v, right: 14.h)), Align(alignment: Alignment.bottomCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 21.v, width: 89.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomCenter, child: Text("lbl_15_may_2023".tr, style: theme.textTheme.bodySmall)), Align(alignment: Alignment.center, child: Container(width: 89.h, padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 1.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_02_may_2023".tr, style: theme.textTheme.bodySmall)))])), _buildTelevisionBooked(context, text: "lbl_book_now".tr)])), SizedBox(height: 14.v), Container(padding: EdgeInsets.all(8.h), decoration: AppDecoration.outlineOnPrimary, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: _buildOpenConference(context, openConferenceText: "lbl_techconnect".tr, technologyText: "lbl_technology".tr)), SizedBox(height: 13.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 19.v, width: 18.h), Padding(padding: EdgeInsets.only(left: 5.h, top: 2.v), child: Text("msg_keramikos_athens".tr, style: theme.textTheme.bodySmall))]), SizedBox(height: 3.v)]))]))])), SizedBox(height: 85.v), _buildEventCategoriesTechnology(context)]))))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 69.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSettings, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_univentures".tr, margin: EdgeInsets.only(left: 18.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgOcticonThreeBars16, margin: EdgeInsets.fromLTRB(33.h, 33.v, 33.h, 32.v), onTap: () {onTapOcticonThreeBarsSixteen(context);})], styleType: Style.bgOutline); } 
/// Section Widget
Widget _buildEventCategoriesTechnology(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 41.h), child: Column(children: [SizedBox(height: 275.v, width: 272.h, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgOpenai1, height: 275.v, width: 272.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 12.h, top: 7.v, right: 12.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPhHeartFillOnprimary, height: 48.v, width: 46.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 1.h)), SizedBox(height: 181.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 23.v, width: 91.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgTelevisionBlueGray100, height: 23.v, width: 91.h, radius: BorderRadius.circular(11.h), alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_02_may_2023".tr, style: theme.textTheme.bodySmall)))])), _buildTelevisionBooked(context, text: "lbl_booked".tr)])])))])), Container(padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 5.v), decoration: AppDecoration.outlineOnPrimary, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: _buildOpenConference(context, openConferenceText: "lbl_open_conference".tr, technologyText: "lbl_technology".tr)), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMdiLocationRadiusOutline, height: 19.v, width: 18.h), Padding(padding: EdgeInsets.only(left: 3.h, bottom: 2.v), child: Text("msg_megaro_mousikis".tr, style: theme.textTheme.bodySmall))])), SizedBox(height: 11.v)]))])); } 
/// Common widget
Widget _buildTelevisionBooked(BuildContext context, {required String text, }) { return SizedBox(height: 21.v, width: 89.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgTelevisionPrimary, height: 21.v, width: 89.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Text(text, style: theme.textTheme.labelLarge!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1))))])); } 
/// Common widget
Widget _buildOpenConference(BuildContext context, {required String openConferenceText, required String technologyText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(openConferenceText, style: CustomTextStyles.titleMediumBlack900_1.copyWith(color: appTheme.black900)), Text(technologyText, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.black900.withOpacity(0.5)))]); } 
/// Navigates to the homeListScreen when the action is triggered.
onTapOcticonThreeBarsSixteen(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeListScreen, ); } 
 }
