import 'bloc/setup_your_accounttwo_bloc.dart';import 'models/setup_your_accounttwo_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';import 'package:kwstas_s_application2/widgets/custom_outlined_button.dart';import 'package:kwstas_s_application2/widgets/custom_text_form_field.dart';class SetupYourAccounttwoScreen extends StatelessWidget {const SetupYourAccounttwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SetupYourAccounttwoBloc>(create: (context) => SetupYourAccounttwoBloc(SetupYourAccounttwoState(setupYourAccounttwoModelObj: SetupYourAccounttwoModel()))..add(SetupYourAccounttwoInitialEvent()), child: SetupYourAccounttwoScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 44.h, vertical: 26.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgSettings, height: 68.v, width: 45.h), SizedBox(height: 33.v), Container(width: 329.h, margin: EdgeInsets.symmetric(horizontal: 6.h), child: Text("msg_some_more_steps".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.displayMedium)), SizedBox(height: 46.v), SizedBox(height: 63.v, width: 341.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLetsIconsArro, height: 43.v, width: 46.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 14.h)), BlocSelector<SetupYourAccounttwoBloc, SetupYourAccounttwoState, TextEditingController?>(selector: (state) => state.questionOneController, builder: (context, questionOneController) {return CustomTextFormField(width: 341.h, controller: questionOneController, hintText: "msg_no_i_am_not_a_student".tr, hintStyle: theme.textTheme.titleLarge!, textInputAction: TextInputAction.done, alignment: Alignment.center, contentPadding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 16.v));})])), SizedBox(height: 10.v), SizedBox(height: 63.v, width: 341.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLetsIconsArro, height: 43.v, width: 46.h, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 14.h)), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapTwentyEight(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 13.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder31), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("msg_are_you_an_organization".tr, style: theme.textTheme.titleLarge)]))))])), SizedBox(height: 10.v), Container(width: 341.h, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder31), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), TextField(decoration: InputDecoration(
                      labelText: "What do you like?",
                      border: OutlineInputBorder()))])), SizedBox(height: 28.v), CustomOutlinedButton(text: "lbl_finish".tr, buttonStyle: CustomButtonStyles.outlinePrimaryTL312), SizedBox(height: 5.v)])))); } 
/// Navigates to the setupYourAccountOrganizationTwoScreen when the action is triggered.
onTapTwentyEight(BuildContext context) { NavigatorService.pushNamed(AppRoutes.setupYourAccountOrganizationTwoScreen, ); } 
 }
