import 'bloc/camera_bloc.dart';import 'models/camera_model.dart';import 'package:flutter/material.dart';import 'package:kwstas_s_application2/core/app_export.dart';class CameraScreen extends StatelessWidget {const CameraScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CameraBloc>(create: (context) => CameraBloc(CameraState(cameraModelObj: CameraModel()))..add(CameraInitialEvent()), child: CameraScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<CameraBloc, CameraState>(builder: (context, state) {return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: appTheme.deepPurple100, body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: appTheme.deepPurple100, boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.25), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))], image: DecorationImage(image: AssetImage(ImageConstant.imgCamera), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 5.v), Container(decoration: AppDecoration.fillOnPrimary2.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 17.v), Text("lbl_save_photo".tr, style: CustomTextStyles.titleMediumBlack900Medium), SizedBox(height: 12.v), SizedBox(width: 270.h, child: Divider()), SizedBox(height: 7.v), GestureDetector(onTap: () {onTapTxtTakeNew(context);}, child: Text("lbl_take_new".tr, style: CustomTextStyles.bodyLargeLightblueA700)), SizedBox(height: 8.v), Column(children: [SizedBox(width: 270.h, child: Divider()), SizedBox(height: 8.v), GestureDetector(onTap: () {onTapTxtSave(context);}, child: Text("lbl_save".tr, style: CustomTextStyles.titleMediumLightblueA700)), SizedBox(height: 7.v), SizedBox(width: 270.h, child: Divider())])]))])))));}); } 
/// Navigates to the cameraOneScreen when the action is triggered.
onTapTxtTakeNew(BuildContext context) { NavigatorService.pushNamed(AppRoutes.cameraOneScreen, ); } 
/// Navigates to the profileScreen when the action is triggered.
onTapTxtSave(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
 }
